name: Deploy to PROD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOTNET_ENVIRONMENT: production
      ConnectionStrings__CommunityDb: ${{ secrets.CONNECTIONSTRINGS__COMMUNITYDB_PROD }}
      ConnectionStrings__PermissionsDb: ${{ secrets.CONNECTIONSTRINGS__PERMISSIONSDB_PROD }}
      ConnectionStrings__TemplatesDb: ${{ secrets.CONNECTIONSTRINGS__TEMPLATESDB_PROD }}
      DO_HOST: ${{ secrets.DO_HOST }}
      DO_USER: ${{ secrets.DO_USER }}
      DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # NEW: Write the Firebase service account key to a file
      - name: Write Firebase service account key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > ./serviceAccountKey.json

      - name: Publish App
        run: dotnet publish src/Dhanman.MyHome.Api/Dhanman.MyHome.Api.csproj -c Release -r linux-x64 --self-contained false -o publish

      - name: Upload to PROD
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "publish/*"
          target: "/var/www/prod/dhanman-community"
          strip_components: 1

      - name: Restart PROD Service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            export ConnectionStrings__CommunityDb="${{ secrets.CONNECTIONSTRINGS__COMMUNITYDB_PROD }}"
            export ConnectionStrings__PermissionsDb="${{ secrets.CONNECTIONSTRINGS__PERMISSIONSDB_PROD }}"
            export ConnectionStrings__TemplatesDb="${{ secrets.CONNECTIONSTRINGS__TEMPLATESDB_PROD }}"
            export DOTNET_ENVIRONMENT=production
            sudo systemctl restart dhanman-community-prod
            sudo systemctl status dhanman-community-prod --no-pager
