name: Deploy to PROD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod

    env:
      DOTNET_ENVIRONMENT: production
      DO_HOST: ${{ secrets.DO_HOST }}
      DO_USER: ${{ secrets.DO_USER }}
      DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish App
        run: dotnet publish src/Dhanman.MyHome.Api/Dhanman.MyHome.Api.csproj -c Release -r linux-x64 --self-contained false -o publish

      - name: Upload to PROD
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.DO_HOST }}
          username: ${{ env.DO_USER }}
          key: ${{ env.DO_SSH_KEY }}
          source: "publish/*"
          target: "/var/www/prod/dhanman-community"
          strip_components: 1

      - name: Restart PROD Service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.DO_HOST }}
          username: ${{ env.DO_USER }}
          key: ${{ env.DO_SSH_KEY }}
          script: |
            export ConnectionStrings__CommunityDb="${{ secrets.COMMUNITY_DB_CONNECTION }}"
            export ConnectionStrings__PermissionsDb="${{ secrets.PERMISSIONS_DB_CONNECTION }}"
            export DOTNET_ENVIRONMENT=production
            sudo systemctl restart dhanman-community-prod
